### ISSUE TITLE
Can I tell if the patch is being used by the debugger?

### ISSUE THREAD

**Issue by RussellHaley** [devcat-studio/lua-5.3.4-op_halt#1]
Hi, 

I've applied the patch to my Lua build and I can successfully debug my scripts in vscode. Is there any way to verify from the binary lua.exe that the OP_HALT patch is present and also if the devcat debugger is using the new op code?

Thanks for putting patch this together and the vs code debugger. I was interested in Dan Tulls work but couldn't get the patches collected together. 

Russell

**Comment by lee-seungjae** [comment]
[Check the return value of `debuggee.start`.](https://github.com/devcat-studio/VSCodeLuaDebug/blob/master/Extension/README.md#debuggeestartjsonlib-config)
> debuggee.start returns two values. The first return value is true if it is normally connected to the debugger, otherwise it is false. If the OP_HALT patch is applied in the current Lua VM, the second return value is 'halt', otherwise it is 'pure'.

I'm the author of the original lua-5.1.5-op_halt patch, so I'm not sure about this 5.3.4 version. Sorry if this information is wrong.

**Comment by RussellHaley** [comment]
Thank you for the information. Debuggee.start is returning `true pure` so I will need to investigate. I discovered it's possible that this is an unpatched binary. Thank you!

**Comment by RussellHaley** [comment]
I accidentally built Lua under debug configuration and grabbed release output. oops. 

I now get `debuggee start ->       true    halt`. Thanks for your help!
